version: "3"

services:

  developer:
    image: hub.xenit.eu/private/xenit-markdowntopdf:latest
    volumes:
      - ./build/src/developer:/docs:z
    working_dir: /docs
    command: developer-guide.md -o Alfred_Api_Developer_Guide.pdf