version: "3"

services:

  user:
    image: hub.xenit.eu/private/xenit-markdowntopdf:latest
    volumes:
      - ./build/src/user:/docs:z
    working_dir: /docs
    command: user-guide.md --lua-filter latex-h-break.lua -o Alfred_API_User_Guide.pdf